# Generated by Django 4.1.2 on 2022-11-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_date_posted_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image'),
        ),
    ]
