# Generated by Django 4.1.2 on 2022-11-07 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_post_image'),
        ('blog', '0013_alter_post_date_updated'),
    ]

    operations = [
    ]
