# Generated by Django 3.2.5 on 2022-11-14 06:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_merge_20221107_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
