# Generated by Django 4.1.2 on 2022-10-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='image/default.png', null=True, upload_to='image'),
        ),
    ]
